name: course_name
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - pip=22.3.1
  - python=3.10.6
  - readline=8.1.2
  - setuptools=65.5.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
    - absl-py==2.1.0
    - accessible-pygments==0.0.4
    - alabaster==0.7.16
    - anyio==4.2.0
    - appnope==0.1.3
    - arabic-reshaper==3.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blosc2==2.5.1
    - cachetools==5.3.2
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - comm==0.2.1
    - contourpy==1.2.0
    - cryptography==42.0.2
    - cycler==0.12.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docutils==0.18.1
    - dukpy==0.3.0
    - elementpath==4.1.5
    - esprima==4.0.1
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastjsonschema==2.19.1
    - ffpyplayer==4.5.1
    - flatbuffers==23.5.26
    - fonttools==4.47.2
    - fqdn==1.5.1
    - freetype-py==2.4.0
    - future==0.18.3
    - gast==0.5.4
    - gevent==23.9.1
    - gitdb==4.0.11
    - gitpython==3.1.41
    - google-auth==2.27.0
    - google-auth-oauthlib==1.2.0
    - google-pasta==0.2.0
    - greenlet==3.0.3
    - grpcio==1.60.1
    - h5py==3.10.0
    - html2text==2020.1.16
    - idna==3.6
    - imageio==2.33.1
    - imageio-ffmpeg==0.4.9
    - imagesize==1.4.1
    - importlib-metadata==7.0.1
    - ipykernel==6.29.0
    - ipython==8.20.0
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - javascripthon==0.12
    - jedi==0.19.1
    - jinja2==3.1.3
    - joblib==1.3.2
    - json-tricks==3.17.3
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter==1.0.0
    - jupyter-book==0.15.1
    - jupyter-cache==0.6.1
    - jupyter-client==8.6.0
    - jupyter-console==6.6.3
    - jupyter-core==5.7.1
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.2
    - jupyter-server==2.12.5
    - jupyter-server-terminals==0.5.1
    - jupyterlab==4.0.11
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.2
    - jupyterlab-widgets==3.0.9
    - keras==2.15.0
    - kiwisolver==1.4.5
    - latexcodec==2.0.1
    - lazy-loader==0.3
    - libclang==16.0.6
    - linkify-it-py==2.0.2
    - lxml==5.1.0
    - markdown==3.5.2
    - markdown-it-py==2.2.0
    - markupsafe==2.1.4
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.5
    - mdurl==0.1.2
    - mistune==3.0.2
    - ml-dtypes==0.2.0
    - mne==1.6.1
    - mne-bids==0.14
    - msgpack==1.0.7
    - msgpack-numpy==0.4.8
    - myst-nb==0.17.2
    - myst-parser==0.18.1
    - nbclient==0.7.4
    - nbconvert==7.14.2
    - nbformat==5.9.2
    - ndindex==1.7
    - nest-asyncio==1.6.0
    - nibabel==5.2.0
    - nilearn==0.10.3
    - notebook==7.0.7
    - notebook-shim==0.2.3
    - numexpr==2.9.0
    - numpy==1.26.3
    - oauthlib==3.2.2
    - opencv-python==4.9.0.80
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - overrides==7.6.0
    - packaging==23.2
    - pandas==2.2.0
    - pandas-flavor==0.6.0
    - pandocfilters==1.5.1
    - parso==0.8.3
    - patsy==0.5.6
    - pexpect==4.9.0
    - pillow==10.2.0
    - pingouin==0.5.4
    - platformdirs==4.1.0
    - plotly==5.18.0
    - pooch==1.8.0
    - prometheus-client==0.19.0
    - prompt-toolkit==3.0.43
    - protobuf==4.23.4
    - psutil==5.9.8
    - psychopy==2023.2.3
    - psychtoolbox==3.0.19.0
    - ptitprince==0.2.7
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-cpuinfo==9.0.0
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pybtex==0.24.0
    - pybtex-docutils==1.0.3
    - pycparser==2.21
    - pydata-sphinx-theme==0.15.2
    - pyglet==1.5.27
    - pygments==2.17.2
    - pyparsing==3.1.1
    - pypi-search==2.0
    - pyserial==3.5
    - python-bidi==0.4.2
    - python-dateutil==2.8.2
    - python-gitlab==4.4.0
    - python-json-logger==2.0.7
    - python-vlc==3.0.20123
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.2
    - qtconsole==5.5.1
    - qtpy==2.4.1
    - questplus==2023.1
    - referencing==0.32.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.17.1
    - rsa==4.9
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - seaborn==0.11.0
    - send2trash==1.8.2
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - soundfile==0.12.1
    - soupsieve==2.5
    - sphinx==5.0.2
    - sphinx-book-theme==1.0.1
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.5.2
    - sphinx-design==0.3.0
    - sphinx-external-toc==0.3.1
    - sphinx-jupyterbook-latex==0.5.2
    - sphinx-multitoc-numbering==0.1.3
    - sphinx-thebe==0.2.1
    - sphinx-togglebutton==0.3.2
    - sphinxcontrib-applehelp==1.0.8
    - sphinxcontrib-bibtex==2.5.0
    - sphinxcontrib-devhelp==1.0.6
    - sphinxcontrib-htmlhelp==2.0.5
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.7
    - sphinxcontrib-serializinghtml==1.1.10
    - sqlalchemy==2.0.25
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - tables==3.9.2
    - tabulate==0.9.0
    - tenacity==8.2.3
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.0
    - tensorflow-estimator==2.15.0
    - tensorflow-io-gcs-filesystem==0.35.0
    - termcolor==2.4.0
    - terminado==0.18.0
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - tornado==6.4
    - tqdm==4.66.1
    - traitlets==5.14.1
    - types-python-dateutil==2.8.19.20240106
    - typing-extensions==4.9.0
    - tzdata==2023.4
    - uc-micro-py==1.0.2
    - ujson==5.9.0
    - uri-template==1.3.0
    - urllib3==2.1.0
    - wcwidth==0.2.13
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - websockets==12.0
    - werkzeug==3.0.1
    - widgetsnbextension==4.0.9
    - wrapt==1.14.1
    - wxpython==4.2.1
    - xarray==2024.1.1
    - xmlschema==3.0.1
    - zipp==3.17.0
    - zope-event==5.0
    - zope-interface==6.1