#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : course_name  # The title of the book. Will be placed in the left navbar.
author                      : author_name  # The author of the book
copyright                   : "copyright_year"  # Copyright year to be placed in the footer
logo                        : "static/course_graphics/course_name_logo.png"  # A path to the book logo
exclude_patterns            : []  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : True  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : True  # Whether to add a link to your repository button
  use_issues_button         : True  # Whether to add an "open an issue" button
  use_sidebar               : true 
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: true

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)

repository:
  url                       : https://github.com/spark-csd/course_name  # The URL to your book's repository
  path_to_book              : "course"  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings
sphinx:
  recursive_update: true
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite
    # unknown_mime_type - application/vnd.plotly.v1+json and application/vnd.bokehjs_load.v0+json
    # domains - sphinx_proof.domain::prf needs to have `resolve_any_xref` method
    # mime_priority - latex priority not set in myst_nb for text/html, application/javascript
    suppress_warnings: ["mystnb.unknown_mime_type", "myst.domains", "mystnb.mime_priority"]
    copybutton_prompt_text: "$"
    nb_execution_show_tb: True
    nb_execution_timeout: 120
    intersphinx_mapping:
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null
      sd:
        - https://sphinx-design.readthedocs.io/en/latest
        - null
    language: en
    latex_elements:
        preamble: |
          \newcommand\N{\mathbb{N}}
          \newcommand\floor[1]{\lfloor#1\rfloor}
          \newcommand{\bmat}{\left[\begin{array}}
          \newcommand{\emat}{\end{array}\right]}
    # TODO: #917 this path will be the default in sphinx v4
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # However, it is incompatible with the mathjax config below for macros
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    rediraffe_branch: 'master'
    rediraffe_redirects:
      content-types/index.md: file-types/index.md
      content-types/markdown.md: file-types/markdown.md
      content-types/notebooks.ipynb: file-types/notebooks.ipynb
      content-types/myst-notebooks.md: file-types/myst-notebooks.md
      content-types/jupytext.md: file-types/jupytext.Rmd
      content-types/restructuredtext.md: file-types/restructuredtext.md
      customize/toc.md: structure/toc.md
    sd_fontawesome_latex: True

    html_theme_options:
      navigation_with_keys: false


bibtex_bibfiles: 
  - references.bib